INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (1097, 'WebApplication', 'Loop over data set in ${test-data-profile} from index ${left-data} to index ${right-data}', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\",\"left-data\":\"start\", \"right-data\":\"end\"}}', 'forloop', NULL, 'forloop', 1097, 10211, 20165, 30194, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (1098, 'WebApplication', 'Loop over data set in ${test-data-profile} from index start to index end', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\"}}', 'forloop', NULL, 'forloop', 1098, 10212, 20166, 30195, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (10211, 'MobileWeb', 'Loop over data set in ${test-data-profile} from index ${left-data} to index ${right-data}', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\",\"left-data\":\"start\", \"right-data\":\"end\"}}', 'forloop', NULL, 'forloop', 1097, 10211, 20165, 30194, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (10212, 'MobileWeb', 'Loop over data set in ${test-data-profile} from index start to index end', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\"}}', 'forloop', NULL, 'forloop', 1098, 10212, 20166, 30195, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20165, 'AndroidNative', 'Loop over data set in ${test-data-profile} from index ${left-data} to index ${right-data}', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\",\"left-data\":\"start\", \"right-data\":\"end\"}}', 'forloop', NULL, 'forloop', 1097, 10211, 20165, 30194, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20166, 'AndroidNative', 'Loop over data set in ${test-data-profile} from index start to index end', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\"}}', 'forloop', NULL, 'forloop', 1098, 10212, 20166, 30195, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (30194, 'IOSNative', 'Loop over data set in ${test-data-profile} from index ${left-data} to index ${right-data}', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\",\"left-data\":\"start\", \"right-data\":\"end\"}}', 'forloop', NULL, 'forloop', 1097, 10211, 20165, 30194, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (30195, 'IOSNative', 'Loop over data set in ${test-data-profile} from index start to index end', '{\"test-data-for-loop\":{\"test-data-profile\":\"test data profile\"}}', 'forloop', NULL, 'forloop', 1098, 10212, 20166, 30195, '2022-12-02 14:54:08', '2022-12-02 14:54:08', NULL, 'FOR_LOOP');

INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (859,1097,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\",\"start\":\"start\", \"end\":\"end\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (860,1098,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (863,10211,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\",\"start\":\"start\", \"end\":\"end\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (864,10212,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (867,20165,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\",\"start\":\"start\", \"end\":\"end\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (868,20166,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (871,30194,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\",\"start\":\"start\", \"end\":\"end\"}',now(),now());
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (872,30195,'Loop over data set in Add_User_Data_List from index start to index end','In this example, execution run on itreation of test data profile with start index and end index','','{\"test data profile\":\"Add_User_Data_List\"}',now(),now());
